name: Pardora
options:
  bundleIdPrefix: net.pardev
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    DEVELOPMENT_TEAM: QMLVG482FY
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"
targets:
  Pardora:
    type: application
    platform: iOS
    sources:
      - Pardora
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.pardev.pardora
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Pardora/Resources/Info.plist
        MARKETING_VERSION: "0.1"
        CURRENT_PROJECT_VERSION: "1"
  PardoraTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PardoraTests
    dependencies:
      - target: Pardora
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
schemes:
  Pardora:
    build:
      targets:
        Pardora: all
    test:
      targets:
        - PardoraTests
